#!/bin/bash

set -e
set -u

setup() {
  dotfiles=$HOME/.dotfiles

  if [ -d "$dotfiles" ]; then
    (cd "$dotfiles" && git pull --rebase)
  else
    git clone https://github.com/YOUR_ACCOUNT/.dotfiles "$dotfiles"
  fi
}

setup
