[[plugins]]
repo = 'mattn/emmet-vim'
on_ft = [
  'javascript',
  'javascript.jsx',
  'typescript',
  'typescript.tsx',
  'vue',
  'html'
]

[[plugins]]
repo = 'pangloss/vim-javascript'
on_ft = ['javascript', 'javascript.jsx']

[[plugins]]
repo = 'maxmellon/vim-jsx-pretty'
on_ft = ['javascript', 'javascript.jsx']

[[plugins]]
repo = 'HerringtonDarkholme/yats.vim'
on_ft = ['typescript', 'typescript.tsx', 'vue']

[[plugins]]
repo = 'mhartington/nvim-typescript'
on_ft = ['typescript', 'typescript.tsx', 'vue']
build = './install.sh'
hook_add = '''
  let g:nvim_typescript#diagnostics_enable = 0
  let g:nvim_typescript#vue_support = 1
'''

# [[plugins]]
# repo = 'styled-components/vim-styled-components'
# on_ft = ['javascript', 'javascript.jsx' 'typescript', 'typescript.tsx']

[[plugins]]
repo = 'posva/vim-vue'
on_ft = ['vue']
hook_add = 'autocmd FileType vue syntax sync fromstart'

[[plugins]]
repo = 'tikhomirov/vim-glsl'
on_ft = ['glsl']

[[plugins]]
repo = 'fatih/vim-go'
on_ft = ['go']

[[plugins]]
repo = 'zchee/deoplete-go'
on_ft = ['go']

[[plugins]]
repo = 'cespare/vim-toml'
on_ft = ['toml']
