[[plugins]]
repo = 'mattn/emmet-vim'

[[plugins]]
repo = 'othree/yajs.vim'

[[plugins]]
repo = 'othree/es.next.syntax.vim'

[[plugins]]
repo = 'maxmellon/vim-jsx-pretty'

[[plugins]]
repo = 'carlitux/deoplete-ternjs'

[[plugins]]
repo = 'leafgarland/typescript-vim'

[[plugins]]
repo = 'Quramy/tsuquyomi'

[[plugins]]
repo = 'styled-components/vim-styled-components'

[[plugins]]
repo = 'leafgarland/typescript-vim'

[[plugins]]
repo = 'tikhomirov/vim-glsl'

[[plugins]]
repo = 'fatih/vim-go'

[[plugins]]
repo = 'zchee/deoplete-go'
