[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'Shougo/deoplete.nvim'
do = ':UpdateRemotePlugins'

[[plugins]]
repo = 'Shougo/vimproc.vim'

[[plugins]]
repo = 'tomasr/molokai'

[[plugins]]
repo = 'scrooloose/nerdtree'

[[plugins]]
repo = 'airblade/vim-gitgutter'

[[plugins]]
repo = 'lilydjwg/colorizer'

[[plugins]]
repo = 'tomtom/tcomment_vim'

[[plugins]]
repo = 'bling/vim-airline'

[[plugins]]
repo = 'tpope/vim-fugitive'

[[plugins]]
repo = 'ctrlpvim/ctrlp.vim'
